<?php

namespace App\Http\Requests\Api;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class PumpUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
//            'TypeHP' => [],
//            'rekupMode' => [],
//            'blockPLow' => [],
//            'blockPHigh' => [],
//            'blockT0' => [],
//            'blockT1' => [],
//            'blockT2' => [],
//            'blockT3' => [],
//            'blockT4' => [],
//            'blockT5' => [],
//            'blockT6' => [],
//            'blockT7' => [],
//            'blockT8' => [],
//            'blockT9' => [],
//            'blockT10' => [],
//            'blockT11' => [],
//            'p1_lo' => [],
//            'p2_hi' => [],
//            'ustavOverheat' => [],
//            'typeComp' => [],
//            'minfrequency1' => [],
//            'maxfrequency1' => [],
//            'ustavkiPredAlarm' => [],
//            'minTimeStop' => [],
//            'maxDavlenie' => [],
//            'povtorniyPusk' => [],
//            'shagPriVkl' => [],
//            'maxStep' => [],
//            'gistStep' => [],
//            'intervalEEV' => [],
//            'stepEEV' => [],
//            'saveMinRPM1' => [],
//            'autoRPM1' => [],
//            'minRPM1' => [],
//            'maxRPM1' => [],
//            'ogrMinMax1' => [],
//            'voltageMinRPM1' => [],
//            'voltageMaxRPM1' => [],
//            'KRPM1' => [],
//            'P351' => [],
//            'P361' => [],
//            'saveMinRPM2' => [],
//            'autoRPM2' => [],
//            'minRPM2' => [],
//            'maxRPM2' => [],
//            'ogrMinMax2' => [],
//            'voltageMinRPM2' => [],
//            'voltageMaxRPM2' => [],
//            'KRPM2' => [],
//            'P352' => [],
//            'P362' => [],
//            'PeriodLeg' => [],
//            'timeHLeg' => [],
//            'ustavTempBakGVS' => [],
//            'viderzhka' => [],
//            'P41' => [],
//            'I42' => [],
//            'D43' => [],
//            'P44' => [],
//            'I45' => [],
//            'D46' => [],
//            'P47' => [],
//            'I48' => [],
//            'D49' => [],
//            'zNaruzhTempObogrevMin' => [],
//            'zNaruzhTempObogrevMax' => [],
//            'zNaruzhTempOhlazhMin' => [],
//            'zNaruzhTempOhlazhMax' => [],
//            'OtPhiBar' => [],
//            'DoPhiBar' => [],
//            'OtPloBar' => [],
//            'DoPloBar' => [],
//            'zFreonTempNagMin' => [],
//            'zFreonTempNagMax' => [],
//            'zFreonTempVozMin' => [],
//            'zFreonTempVozMax' => [],
//            'zTeplonosMin' => [],
//            'zTeplonosMax' => [],
//            'zGVSMax' => [],
//            'zadderzhkaDatProtoka' => [],
//            'zBoilerSpeed' => [],
//            'zBoilerTempMax' => [],
//            'zTeplonosPrevBoiler' => [],
//            'zMaxPerepadTempNaCond' => [],
//            'TENintervalVkl' => [],
//            'PredelSpeedTen' => [],
//            'OttaikaTOTempStart' => [],
//            'OttaikaTOTempStop' => [],
//            'zTOTime' => [],
//            'OttaikaPoddonTempStart' => [],
//            'OttaikaPoddonTempStop' => [],
//            'zPoddonTime' => [],
//            'EVITempIsparitel' => [],
//            'EVITempCondensator' => [],
//            'zGidromoduleT2Min' => [],
//            'zGidromoduleT2Max' => [],
//            'zGidromoduleT3Min' => [],
//            'zGidromoduleT3Max' => [],
//            'zGeliokollector' => [],
//            'rotorTeplo' => [],
//            'oxygenBypass' => [],
//            'FileStop' => [],
//            'ottaikaTempT3' => [],
//            'ottaikaDeltaTempT3' => [],
//            'dlitelnostOttaiki' => [],
//            'OborotyRotorOttaiki' => [],
//            'zashitaT9Min' => [],
//            'zashitaT9Max' => [],
//            'P93' => [],
//            'P94' => [],
//            'P95' => [],
//            'P96' => [],
//            'P97' => [],
//            'P98' => [],
//            'P99' => [],
//            'DurationMin' => [],
//            'P101' => [],
//            'P102' => [],
//            'SposobFComp' => [],
//            'SposobVE' => [],
//            'SposobERV' => [],
//            'Zapret' => [],
//            'Zapret_Razr' => [],
//            'TEN' => [],
//            'TEN2' => [],
//            'GVSBox' => [],
//            'P111' => [],
//            'P112' => [],
//            'Gista' => [],
//            'P78' => [],
//            'P114' => [],
//            'P115' => [],

            'ON' => [],
            'TrgT' => [],
            'Boiler' => [],
            'BoilerTRG' => [],
            'table' => [],
            'engParams' => [],
            'resetParams' => [],
            'T0' => [],
            'T1' => [],
            'T2' => [],
            'T3' => [],
            'T4' => [],
            'T5' => [],
            'T6' => [],
            'T7' => [],
            'T8' => [],
            'T9' => [],
            'T10' => [],
            'T11' => [],
            'readParams' => [],
            'modeHP' => [],
            'error' => [],
            'errcode' => [],
            'status' => [],
            'WORK' => [],
            'listProf' => [],
            'PL' => [],
            'PH' => [],
            'OverheatData' => [],
            'TrgtTN' => [],
            'EEVdata' => [],
            'CentralOtop' => [],
            'TempHum' => [],
            'TargetHum' => [],
            'directionn' => [],
            'compWork1' => [],
            'compWork2' => [],
            'tenDog1' => [],
            'tenDog2' => [],
            'tenPod' => [],
            'pumpOUT' => [],
            'pumpIN' => [],
            'pumpHelio' => [],
            'fan' => [],
            'mode3x' => [],
            'fan1' => [],
            'fan2' => [],
            'airValve1' => [],
            'airValve2' => [],
            'airValve3' => [],
            'airValve4' => [],
            'TempAmb' => [],
            'TempModule' => [],
            'Current' => [],
            'CurrentHz' => [],
            'AO1' => [],
            'AO2' => [],
        ];
    }

    public function messages()
    {
        return [
        ];
    }

    public function failedValidation($validator)
    {
        throw new HttpResponseException(
            response()->json(['message' => $validator->errors()->first()], 400)
        );
    }
}
