<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class PumpUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'engineer_parameter.TypeHP' => [],
            'engineer_parameter.rekupMode' => [],
            'engineer_parameter.blockPLow' => [],
            'engineer_parameter.blockPHigh' => [],
            'engineer_parameter.blockT0' => [],
            'engineer_parameter.blockT1' => [],
            'engineer_parameter.blockT2' => [],
            'engineer_parameter.blockT3' => [],
            'engineer_parameter.blockT4' => [],
            'engineer_parameter.blockT5' => [],
            'engineer_parameter.blockT6' => [],
            'engineer_parameter.blockT7' => [],
            'engineer_parameter.blockT8' => [],
            'engineer_parameter.blockT9' => [],
            'engineer_parameter.blockT10' => [],
            'engineer_parameter.blockT11' => [],
            'engineer_parameter.p1_lo' => [],
            'engineer_parameter.p2_hi' => [],
            'engineer_parameter.ustavOverheat' => [],
            'engineer_parameter.typeComp' => [],
            'engineer_parameter.minfrequency1' => [],
            'engineer_parameter.maxfrequency1' => [],
            'engineer_parameter.ustavkiPredAlarm' => [],
            'engineer_parameter.minTimeStop' => [],
            'engineer_parameter.maxDavlenie' => [],
            'engineer_parameter.povtorniyPusk' => [],
            'engineer_parameter.shagPriVkl' => [],
            'engineer_parameter.maxStep' => [],
            'engineer_parameter.gistStep' => [],
            'engineer_parameter.intervalEEV' => [],
            'engineer_parameter.stepEEV' => [],
            'engineer_parameter.saveMinRPM1' => [],
            'engineer_parameter.autoRPM1' => [],
            'engineer_parameter.minRPM1' => [],
            'engineer_parameter.maxRPM1' => [],
            'engineer_parameter.ogrMinMax1' => [],
            'engineer_parameter.voltageMinRPM1' => [],
            'engineer_parameter.voltageMaxRPM1' => [],
            'engineer_parameter.KRPM1' => [],
            'engineer_parameter.P351' => [],
            'engineer_parameter.P361' => [],
            'engineer_parameter.saveMinRPM2' => [],
            'engineer_parameter.autoRPM2' => [],
            'engineer_parameter.minRPM2' => [],
            'engineer_parameter.maxRPM2' => [],
            'engineer_parameter.ogrMinMax2' => [],
            'engineer_parameter.voltageMinRPM2' => [],
            'engineer_parameter.voltageMaxRPM2' => [],
            'engineer_parameter.KRPM2' => [],
            'engineer_parameter.P352' => [],
            'engineer_parameter.P362' => [],
            'engineer_parameter.PeriodLeg' => [],
            'engineer_parameter.timeHLeg' => [],
            'engineer_parameter.ustavTempBakGVS' => [],
            'engineer_parameter.viderzhka' => [],
            'engineer_parameter.P41' => [],
            'engineer_parameter.I42' => [],
            'engineer_parameter.D43' => [],
            'engineer_parameter.P44' => [],
            'engineer_parameter.I45' => [],
            'engineer_parameter.D46' => [],
            'engineer_parameter.P47' => [],
            'engineer_parameter.I48' => [],
            'engineer_parameter.D49' => [],
            'engineer_parameter.zNaruzhTempObogrevMin' => [],
            'engineer_parameter.zNaruzhTempObogrevMax' => [],
            'engineer_parameter.zNaruzhTempOhlazhMin' => [],
            'engineer_parameter.zNaruzhTempOhlazhMax' => [],
            'engineer_parameter.OtPhiBar' => [],
            'engineer_parameter.DoPhiBar' => [],
            'engineer_parameter.OtPloBar' => [],
            'engineer_parameter.DoPloBar' => [],
            'engineer_parameter.zFreonTempNagMin' => [],
            'engineer_parameter.zFreonTempNagMax' => [],
            'engineer_parameter.zFreonTempVozMin' => [],
            'engineer_parameter.zFreonTempVozMax' => [],
            'engineer_parameter.zTeplonosMin' => [],
            'engineer_parameter.zTeplonosMax' => [],
            'engineer_parameter.zGVSMax' => [],
            'engineer_parameter.zadderzhkaDatProtoka' => [],
            'engineer_parameter.zBoilerSpeed' => [],
            'engineer_parameter.zBoilerTempMax' => [],
            'engineer_parameter.zTeplonosPrevBoiler' => [],
            'engineer_parameter.zMaxPerepadTempNaCond' => [],
            'engineer_parameter.TENintervalVkl' => [],
            'engineer_parameter.PredelSpeedTen' => [],
            'engineer_parameter.OttaikaTOTempStart' => [],
            'engineer_parameter.OttaikaTOTempStop' => [],
            'engineer_parameter.zTOTime' => [],
            'engineer_parameter.OttaikaPoddonTempStart' => [],
            'engineer_parameter.OttaikaPoddonTempStop' => [],
            'engineer_parameter.zPoddonTime' => [],
            'engineer_parameter.EVITempIsparitel' => [],
            'engineer_parameter.EVITempCondensator' => [],
            'engineer_parameter.zGidromoduleT2Min' => [],
            'engineer_parameter.zGidromoduleT2Max' => [],
            'engineer_parameter.zGidromoduleT3Min' => [],
            'engineer_parameter.zGidromoduleT3Max' => [],
            'engineer_parameter.zGeliokollector' => [],
            'engineer_parameter.rotorTeplo' => [],
            'engineer_parameter.oxygenBypass' => [],
            'engineer_parameter.FileStop' => [],
            'engineer_parameter.ottaikaTempT3' => [],
            'engineer_parameter.ottaikaDeltaTempT3' => [],
            'engineer_parameter.dlitelnostOttaiki' => [],
            'engineer_parameter.OborotyRotorOttaiki' => [],
            'engineer_parameter.zashitaT9Min' => [],
            'engineer_parameter.zashitaT9Max' => [],
            'engineer_parameter.P93' => [],
            'engineer_parameter.P94' => [],
            'engineer_parameter.P95' => [],
            'engineer_parameter.P96' => [],
            'engineer_parameter.P97' => [],
            'engineer_parameter.P98' => [],
            'engineer_parameter.P99' => [],
            'engineer_parameter.DurationMin' => [],
            'engineer_parameter.P101' => [],
            'engineer_parameter.P102' => [],
            'engineer_parameter.SposobFComp' => [],
            'engineer_parameter.SposobVE' => [],
            'engineer_parameter.SposobERV' => [],
            'engineer_parameter.Zapret' => [],
            'engineer_parameter.Zapret_Razr' => [],
            'engineer_parameter.TEN' => [],
            'engineer_parameter.TEN2' => [],
            'engineer_parameter.GVSBox' => [],
            'engineer_parameter.P111' => [],
            'engineer_parameter.P112' => [],
            'engineer_parameter.Gista' => [],
            'engineer_parameter.P78' => [],
            'engineer_parameter.P114' => [],
            'engineer_parameter.P115' => [],





            'working_parameter.ON' => [],
            'working_parameter.TrgT' => [],
            'working_parameter.Boiler' => [],
            'working_parameter.BoilerTRG' => [],
            'working_parameter.table' => [],
            'working_parameter.engParams' => [],
            'working_parameter.resetParams' => [],
            'working_parameter.T0' => [],
            'working_parameter.T1' => [],
            'working_parameter.T2' => [],
            'working_parameter.T3' => [],
            'working_parameter.T4' => [],
            'working_parameter.T5' => [],
            'working_parameter.T6' => [],
            'working_parameter.T7' => [],
            'working_parameter.T8' => [],
            'working_parameter.T9' => [],
            'working_parameter.T10' => [],
            'working_parameter.T11' => [],
            'working_parameter.readParams' => [],
            'working_parameter.modeHP' => [],
            'working_parameter.error' => [],
            'working_parameter.errcode' => [],
            'working_parameter.status' => [],
            'working_parameter.WORK' => [],
            'working_parameter.listProf' => [],
            'working_parameter.PL' => [],
            'working_parameter.PH' => [],
            'working_parameter.OverheatData' => [],
            'working_parameter.TrgtTN' => [],
            'working_parameter.EEVdata' => [],
            'working_parameter.CentralOtop' => [],
            'working_parameter.TempHum' => [],
            'working_parameter.TargetHum' => [],
            'working_parameter.directionn' => [],
            'working_parameter.compWork1' => [],
            'working_parameter.compWork2' => [],
            'working_parameter.tenDog1' => [],
            'working_parameter.tenDog2' => [],
            'working_parameter.tenPod' => [],
            'working_parameter.pumpOUT' => [],
            'working_parameter.pumpIN' => [],
            'working_parameter.pumpHelio' => [],
            'working_parameter.fan' => [],
            'working_parameter.mode3x' => [],
            'working_parameter.fan1' => [],
            'working_parameter.fan2' => [],
            'working_parameter.airValve1' => [],
            'working_parameter.airValve2' => [],
            'working_parameter.airValve3' => [],
            'working_parameter.airValve4' => [],
            'working_parameter.TempAmb' => [],
            'working_parameter.TempModule' => [],
            'working_parameter.Current' => [],
            'working_parameter.CurrentHz' => [],
            'working_parameter.AO1' => [],
            'working_parameter.AO2' => [],
        ];
    }

    public function messages()
    {
        return [
        ];
    }
}
